site:
  title: JF Team
  url: https://jeferro.github.io/doc-jeferro/
  start_page: docs:ROOT:home.adoc

content:
  sources:
    - url: .
      start_path: docs

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
  extensions:
    - ./extensions/asciidoc-extension-grid.js
ui:
  bundle:
    url: ./ui-bundle
    snapshot: true
