
= Deployment

== Firebase
Como primer paso, después de crear un nuevo proyecto en Firebase, debemos registrar una nueva aplicación Javascript en en proyecto para obtener los datos de configuración de la conexión de la SPA a Firebase.

Y a continuación, activar los siguientes módulos:



=== Autenticación

Activar la autenticación tipo _"correo electrónico/contraseña"_.



=== Firestore Database

==== Configuración

* modo: producción
* ubicación: eur3 (europe-west)


==== Índices

[cols="1,1,1"]
|===
|Id colección |Campos indexados |Alcance de la consulta

|summaries
|userId: Ascendente, code: Descendente
|Colección

|operations
|userId: Ascendente, date: Descendente
|Colección
|===


==== Reglas

[source,javascript]
----
rules_version = '2';
service cloud.firestore {
	// True if the user is authenticated
  function isAuthenticated(){
    return request.auth != null
    	&& request.auth.uid != null;
  }

  // True if the user is authenticated and an administrator
  function isAnAdmin(database){
    return isAuthenticated()
      && get(/databases/$(database)/documents/users/$(request.auth.uid)).data.admin == true;
  }

  // True if the user is authenticated user
  function isTheUser(userId){
    return isAuthenticated()
      && (request.auth.uid == userId);
  }
  
  // True if the new resource is owned by the authenticated user
  function isOwnedNewResource(){
  	return request.resource.data.userId == request.auth.uid;
  }

  // True if the resource is owned by the authenticated user or resource does not exist
  function isOwnedResource(database){
      return isAuthenticated()
        && ((resource == null) || (resource.data.userId == request.auth.uid));
  }
    
    

  // COLLECTIONS
  match /databases/{database}/documents {
    
    // --- Users
    match /users/{userId} {      
      allow create, read, update: if isTheUser(userId);
      
      allow delete: if false;
    }
    
    // --- Operations
    match /operations/{operationId} {
      allow create: if isOwnedNewResource();
    	allow read, update, delete: if isOwnedResource(database);
    }
    
    // --- Summaries
    match /summaries/{summaryId} {
      allow create: if isOwnedNewResource();
    	allow read, update, delete: if isOwnedResource(database);
    }
  }
}
----



=== Hosting

Establecer a _"3"_ la opción _"Configuración de almacenamiento de actualizaciones"_ en el historial de actualizaciones del dominio.