
= Configuraci贸n

== GitHub

=== Tags

En la secci贸n "Issues -> Labels" se deben dejar unicamente los siguientes tags definidos:

[cols="1,1"]
|===
| Label name
| Color

| hotfix
| #d73a4a

| feature
| #0E8A16

| bugfix
| #FE5CE6

| release
| #FBCA04

| automated
| #5319E7
|===


=== Firebase

Para los despliegues en Firebase, debemos crear un nuevo secret con el token de autenticaci贸n de Firebase.

Entonces, como primer paso debemos crear el nuevo token:

[code,bash]
----
npx firebase-tools login:ci
----

Y crear un nuevo secret en Github (Settings -> Secrets -> Actions):

* Nombre: FIREBASE_TOKEN
* Valor: token generado



=== PAT del workflow

Algunos workflows del CI/CD realizan operaciones sobre GitHub: creaci贸n de PR, comentarios, etc. Por esto se necesita un Personal Access Token o de una cuenta ya existe o idealmente de una nueva cuenta que identifique al usuario bot.

Para generar el access token, se debe acceder a Settings -> Developer Settings -> Personal access tokens.

Tras lo cual, debemos crear un nuevo secret en GitHub (Settings -> Secrets -> Actions):

* Nombre: CICD_GITHUB_TOKEN
* Valor: PAT generado